version: 2
registries:
  github-axiom:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.AXIOM_READONLY_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 12
    cooldown:
      default-days: 0
    registries:
      - github-axiom
